### ISSUE TITLE
Lupa not working in os 10.13

### ISSUE THREAD

**Issue by sauliuni** [scoder/lupa#99]
Hello,

i wanted to use lupa 1.5 package on my mac ( running 10.13). But after trying this:

```
import lupa
from lupa import LuaRuntime
lua = LuaRuntime(unpack_returned_tuples=True)
```

I get following error:

> dyld: lazy symbol binding failed: Symbol not found: _luaL_openlib
  Referenced from: /usr/local/lib/python3.6/site-packages/lupa/_lupa.cpython-36m-darwin.so
  Expected in: flat namespace
dyld: Symbol not found: _luaL_openlib
  Referenced from: /usr/local/lib/python3.6/site-packages/lupa/_lupa.cpython-36m-darwin.so
  Expected in: flat namespace

Im installed lua via brew (Is now lua 5.3.4), and use python 3.6 virtual environment.

Any ideas what did go wrong?

**Comment by scoder** [comment]
Duplicate of #95.
